config/routes.rb
Rails.application.routes.draw do

  get 'search/index'
  
#reader page configuration

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'users/new'
  get 'signup'  => 'users#new'
  
  resources :users do
    resources :articles do
      resources :comments
    end
  end

  get 'welcome/index'

  root 'welcome#index'

  post 'users/:user_id/articles/:article_id/comments/:id', to: 'tweets#create', as: 'create_user_article_comment_tweet'
  delete 'users/:user_id/articles/:article_id/comments/:comment_id/tweets/:id', to: 'tweets#destroy', as: 'delete_user_article_comment_tweet'
  
  get    'search'   => 'search#index'

  resources :readers do
    resources :tweets
  end

  get    'login_reader'   => 'sessions#new_reader'
  post   'login_reader'   => 'sessions#create_reader'
  delete 'logout_reader'  => 'sessions#destroy_reader'
  get 'signupreader'  => 'readers#new'
  post 'create_reader'  => 'readers#create'


#mypage configuration

  namespace :mypage do
    resources :users do
      resources :articles do
        resources :comments
      end
    end
  end
  
  post '/mypage/users/:user_id/articles', to: 'mypage/articles#create', as: 'create_mypage_user_article'
  patch '/mypage/users/:user_id/articles/:id', to: 'mypage/articles#update', as: 'update_mypage_user_article'
  
  post '/mypage/users/:user_id/articles/:article_id/comments', to: 'mypage/comments#create', as: 'create_mypage_user_article_comment'
  patch '/mypage/users/:user_id/articles/:article_id/comments/:id', to: 'mypage/comments#update', as: 'update_mypage_user_article_comment'
  
  get '/mypage/users/:user_id/configurations', to: 'mypage/configurations#show', as: 'mypage_user_configuration'
  get '/mypage/users/:user_id/configurations/edit', to: 'mypage/configurations#edit', as: 'edit_mypage_user_configuration'
  patch '/mypage/users/:user_id/configurations', to: 'mypage/configurations#update', as: 'update_mypage_user_configuration'

end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :tweets
  belongs_to :article
  
  def previous(articleid)
    Comment.where("id < ? AND article_id == ?", self.id, articleid).order("id DESC").first
  end
 
  def next(articleid)
    Comment.where("id > ? AND article_id == ?", self.id, articleid).order("id ASC").first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def show
    @user = User.find(params[:user_id])
    @article = @user.articles.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
  end

  private
  
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
  
  def search_params
    params.permit(:user_id)
  end

  def target_user
    User.find(search_params[:user_id])
  end

end

app/controllers/mypage/comments_controller.rb
class Mypage::CommentsController < ApplicationController

  def show
    @user = User.find(params[:user_id])
    @article = target_user.articles.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @article = target_user.articles.find(params[:article_id])
    @comment = @article.comments.new
  end

  def edit
    @user = User.find(params[:user_id])
    @article = target_user.articles.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
  end

  def create
    @user = User.find(params[:user_id])
    @article = target_user.articles.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to mypage_user_article_path(@user, @article)
  end

  def update
    @user = User.find(params[:user_id])
    @article = target_user.articles.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    
    if @comment.update(comment_params)
      redirect_to mypage_user_article_comment_path(@user, @article, @comment)
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @article = target_user.articles.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to mypage_user_article_path(@user, @article)
  end

  private
  
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
  
  def search_params
    params.permit(:user_id)
  end

  def target_user
    User.find(search_params[:user_id])
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/mypage/comments_helper.rb
module Mypage::CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <!--<%= form.label :commenter %><br>-->
    小タイトル<br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <!--<%= form.label :body %><br>-->
    本文<br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/show.html.erb
<% provide(:title, "#{@article.title}_#{@comment.commenter}") %>
  <div class="container2">
    <nav id="nav2">
      <%= link_to "#{@user.name}さんのホーム", user_path(@user) %>/<%= link_to @article.title, user_article_path(@user, @article) %>/<%= link_to @comment.commenter, user_article_comment_path(@user, @article, @comment) %>
    </nav>
  </div>
  <div class="dummy">
  </div>
</header>
  <div class="reader_comment_main">
    <h1><%= @comment.commenter %></h1>
    <% if @comment.previous(@comment.article_id).nil? && @comment.next(@comment.article_id).nil? %>
    <% elsif @comment.previous(@comment.article_id).nil? %>
      <%= link_to "次の話へ", user_article_comment_path(@user, @article, @comment.next(@comment.article_id)) %>
    <% elsif @comment.next(@comment.article_id).nil? %>
      <%= link_to "前の話へ", user_article_comment_path(@user, @article, @comment.previous(@comment.article_id)) %>
    <% else %>
      <%= link_to "前の話へ", user_article_comment_path(@user, @article, @comment.previous(@comment.article_id)) %>
      <%= link_to "次の話へ", user_article_comment_path(@user, @article, @comment.next(@comment.article_id)) %>
    <% end %>
    <p>
      本文<br>
      <%= @comment.body %>
    </p>
    <p>コメント一覧</p>
    <ul>
      <% @comment.tweets.each do |tweet| %>
        <li><%= tweet.commenter %>さんのコメント：<%= tweet.body %><%= link_to "削除する", delete_user_article_comment_tweet_path(@user, @article, @comment, tweet), method: :delete, data: { confirm: 'Are you sure?' } %></li>
      <% end %>
    </ul>
    <% if is_logged_in_reader? %>
      <%= form_with model: [ @comment, @comment.tweets.build ], url: create_user_article_comment_tweet_path, local: true do |form| %>
        <p>
          <%= form.hidden_field :commenter, :value => current_reader.name %>
        </p>
        <p>
          コメント<br>
          <%= form.text_area :body %>
        </p>
        <p>
          <%= form.submit %>
          <%= form.hidden_field :reader_id, :value => current_reader.id %>
        </p>
      <% end %>
    <% end %>
    <%= link_to '小説タイトルに戻る', user_article_path(@user, @article) %>
  </div>