config/routes.rb
Rails.application.routes.draw do

  get 'search/index'
  
#reader page configuration

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'users/new'
  get 'signup'  => 'users#new'
  
  resources :users do
    resources :articles do
      resources :comments
    end
  end

  get 'welcome/index'

  root 'welcome#index'

  post 'users/:user_id/articles/:article_id/comments/:id', to: 'tweets#create', as: 'create_user_article_comment_tweet'
  delete 'users/:user_id/articles/:article_id/comments/:comment_id/tweets/:id', to: 'tweets#destroy', as: 'delete_user_article_comment_tweet'
  
  get    'search'   => 'search#index'

  resources :readers do
    resources :tweets
  end

  get    'login_reader'   => 'sessions#new_reader'
  post   'login_reader'   => 'sessions#create_reader'
  delete 'logout_reader'  => 'sessions#destroy_reader'
  get 'signupreader'  => 'readers#new'
  post 'create_reader'  => 'readers#create'


#mypage configuration

  namespace :mypage do
    resources :users do
      resources :articles do
        resources :comments
      end
    end
  end
  
  post '/mypage/users/:user_id/articles', to: 'mypage/articles#create', as: 'create_mypage_user_article'
  patch '/mypage/users/:user_id/articles/:id', to: 'mypage/articles#update', as: 'update_mypage_user_article'
  
  post '/mypage/users/:user_id/articles/:article_id/comments', to: 'mypage/comments#create', as: 'create_mypage_user_article_comment'
  patch '/mypage/users/:user_id/articles/:article_id/comments/:id', to: 'mypage/comments#update', as: 'update_mypage_user_article_comment'
  
  get '/mypage/users/:user_id/configurations', to: 'mypage/configurations#show', as: 'mypage_user_configuration'
  get '/mypage/users/:user_id/configurations/edit', to: 'mypage/configurations#edit', as: 'edit_mypage_user_configuration'
  patch '/mypage/users/:user_id/configurations', to: 'mypage/configurations#update', as: 'update_mypage_user_configuration'

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :category,  presence: true
  validates :status, inclusion:{in: [true, false]}
  enum category: {純文学:1, ミステリー:2, 青春:3, 恋愛:4, SF:5, ファンタジー:6, ホラー:7, ライトノベル:8, 
                      経済:9, 政治:10, 歴史:11, 児童:12, 官能:13}
  def self.search(search, category)
    if search != "" && category != ""
      return Article.where("text LIKE ?", "%#{search}%").where("category LIKE ?", "#{category}")
    elsif search != "" && category == ""
      return Article.where("text LIKE ?", "%#{search}%")
    elsif search == "" && category != ""
      return Article.where("category LIKE ?", "#{category}")
    else
      return Article.all
    end
  end  
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def show
    @user = User.find(params[:user_id])
    @article = target_user.articles.find(params[:id])
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end

  def search_params
    params.permit(:user_id)
  end

  def target_user
    User.find(search_params[:user_id])
  end
end

app/controllers/mypage/articles_controller.rb
class Mypage::ArticlesController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @articles = target_user.articles || Article.all
    @tweets = @user.tweets.all
  end

  def show
    @user = User.find(params[:user_id])
    @article = target_user.articles.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @article = target_user.articles.new
    @categories = [:純文学, :ミステリー, :青春, :恋愛, :SF, :ファンタジー, :ホラー, :ライトノベル, 
                      :経済, :政治, :歴史, :児童, :官能]
  end

  def edit
    @user = User.find(params[:user_id])
    @article = target_user.articles.find(params[:id])
    @categories = [:純文学, :ミステリー, :青春, :恋愛, :SF, :ファンタジー, :ホラー, :ライトノベル, 
                      :経済, :政治, :歴史, :児童, :官能]
  end

  def create
    @user = User.find(params[:user_id])
    @article = target_user.articles.create(article_params)

    if @article.save
      redirect_to mypage_user_articles_url
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:user_id])
    @article = target_user.articles.find(params[:id])
    if @article.update(article_params)
      redirect_to mypage_user_article_url
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @article = @user.articles.find(params[:id])
    @article.destroy

    redirect_to mypage_user_articles_url
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :category, :status)
  end

  def search_params
    params.permit(:user_id)
  end

  def target_user
    User.find(search_params[:user_id])
  end

end

app/controllers/mypage/comments_controller.rb
class Mypage::CommentsController < ApplicationController

  def show
    @user = User.find(params[:user_id])
    @article = target_user.articles.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @article = target_user.articles.find(params[:article_id])
    @comment = @article.comments.new
  end

  def edit
    @user = User.find(params[:user_id])
    @article = target_user.articles.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
  end

  def create
    @user = User.find(params[:user_id])
    @article = target_user.articles.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to mypage_user_article_path(@user, @article)
  end

  def update
    @user = User.find(params[:user_id])
    @article = target_user.articles.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    
    if @comment.update(comment_params)
      redirect_to mypage_user_article_comment_path(@user, @article, @comment)
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @article = target_user.articles.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to mypage_user_article_path(@user, @article)
  end

  private
  
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
  
  def search_params
    params.permit(:user_id)
  end

  def target_user
    User.find(search_params[:user_id])
  end

end

app/controllers/mypage/configurations_controller.rb
class Mypage::ConfigurationsController < ApplicationController

  def show
    @user = User.find(params[:user_id])
  end

  def edit
    @user = User.find(params[:user_id])
  end

  def update
    @user = User.find(params[:user_id])

    if @user.update(user_params)
      redirect_to mypage_user_configuration_url(@user)
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/mypage/articles_helper.rb
module Mypage::ArticlesHelper
end

app/helpers/mypage/comments_helper.rb
module Mypage::CommentsHelper
end

app/helpers/mypage/configurations_helper.rb
module Mypage::ConfigurationsHelper
end

app/views/mypage/articles/edit.html.erb
<% provide(:title, "#{@article.title}の編集") %>
  <div class="container2">
    <nav id="nav2">
      <%= link_to "#{@user.name}さんのホーム", mypage_user_articles_path(@user) %>/<%= link_to @article.title, mypage_user_article_path(@user, @article) %>
    </nav>
  </div>
  <div class="dummy">
  </div>
</header>
<div class="writer_article_edit_main">
  <h1>小説の編集</h1>
  <%= form_with model: @article, url: update_mypage_user_article_path, local: true do |form| %>
    <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:</h2>
      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
    <p>
      小説のタイトル<br>
      <%= form.text_field :title %>
    </p>
    <p>小説のジャンル</p>
    <% @categories.each do |category| %>
      <%= form.radio_button :category, category %><%= form.label category %>
    <% end%>
    <p>
      あらすじ<br>
      <%= form.text_area :text %>
    </p>
    <p>
      <br>
      <%= form.radio_button :status, false %>連載中　<%= form.radio_button :status, true %>完結済み
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
  <%= link_to '小説のタイトルに戻る', mypage_user_article_path %>
</div>

app/views/mypage/articles/index.html.erb
<% provide(:title, "#{@user.name}さんホーム") %>
  <div class="container2">
    <nav id="nav2">
      <%= link_to "#{@user.name}さんのホーム", mypage_user_articles_path(@user) %>
    </nav>
  </div>
  <div class="dummy">
  </div>
</header>
<%= flash.now[:success] %>
<div class="writer_main">
  <%= link_to 'アカウント画面へ', mypage_user_configuration_path(@user) %>
  <%= link_to "ログアウト", logout_path, method: :delete %>
  <%= link_to '小説を新規作成', new_mypage_user_article_path %>
  <table>
    <tr>
      <th>連載中の小説</th>
      <th>ジャンル</th>
    </tr>
    <% @articles.each do |article| %>
      <% unless article.status %>
      <tr>
        <td><%= link_to article.title, mypage_user_article_path(@user, article) %></td>
        <td><%= article.category %></td>
      </tr>
      <% end %>
    <% end %>
  </table>
  <table>
    <tr>
      <th>完結済みの小説</th>
      <th>ジャンル</th>
    </tr>
    <% @articles.each do |article| %>
      <% unless !article.status %>
      <tr>
        <td><%= link_to article.title, mypage_user_article_path(@user, article) %></td>
        <td><%= article.category %></td>
      </tr>
      <% end %>
    <% end %>
  </table>
  <table>
    <tr>
      <th><%= current_user.name%>さんへのコメント一覧</th>
    </tr>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.commenter %>さん：<%= tweet.body %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/mypage/articles/new.html.erb
<% provide(:title, "小説の新規作成") %>
  <div class="container2">
    <nav id="nav2">
      <%= link_to "#{@user.name}さんのホーム", mypage_user_articles_path(@user) %>
    </nav>
  </div>
  <div class="dummy">
  </div>
</header>
<div class="writer_article_new_main">
  <h1>小説の新規作成</h1>
  <%= form_with model: @article, url: create_mypage_user_article_path, local: true do |form| %>
    <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:</h2>
      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
    <p>
      小説のタイトル<br>
      <%= form.text_field :title %>
    </p>
    <p>小説のジャンル</p>
    <% @categories.each do |category| %>
      <%= form.radio_button :category, category %><%= form.label category %>
    <% end%>
    <p>
      あらすじ<br>
      <%= form.text_area :text %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
  <%= link_to '作者ホームへ戻る', mypage_user_articles_path(@user) %>
</div>

app/views/mypage/articles/show.html.erb
<% provide(:title, "#{@article.title}") %>
  <div class="container2">
    <nav id="nav2">
      <%= link_to "#{@user.name}さんのホーム", mypage_user_articles_path(@user) %>/<%= link_to @article.title, mypage_user_article_path(@user, @article) %>
    </nav>
  </div>
  <div class="dummy">
  </div>
</header>
<div class="writer_article_main">
  <h1>
    <%= @article.title %>
  </h1>
  ジャンル：<%= @article.category %>
  <% if @article.status %>
  <br>完結済み
  <% else %>
  <br>連載中
  <% end %>
  <p>
    <strong>あらすじ<br></strong>
    <%= @article.text %>
  </p>
  <%= link_to '編集する', edit_mypage_user_article_path(@user, @article) %>
  <%= link_to '削除する', mypage_user_article_path(@user, @article), method: :delete, data: { confirm: 'Are you sure?' } %>
  <p><strong>各話</strong> <%= link_to '追加する', new_mypage_user_article_comment_path(@user, @article), method: :get %></p>
  <%= render @article.comments %>
  <%= link_to '作者ホームへ戻る', mypage_user_articles_path %>
</div>