config/routes.rb
Rails.application.routes.draw do

  get 'search/index'
  
#reader page configuration

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'users/new'
  get 'signup'  => 'users#new'
  
  resources :users do
    resources :articles do
      resources :comments
    end
  end

  get 'welcome/index'

  root 'welcome#index'

  post 'users/:user_id/articles/:article_id/comments/:id', to: 'tweets#create', as: 'create_user_article_comment_tweet'
  delete 'users/:user_id/articles/:article_id/comments/:comment_id/tweets/:id', to: 'tweets#destroy', as: 'delete_user_article_comment_tweet'
  
  get    'search'   => 'search#index'

  resources :readers do
    resources :tweets
  end

  get    'login_reader'   => 'sessions#new_reader'
  post   'login_reader'   => 'sessions#create_reader'
  delete 'logout_reader'  => 'sessions#destroy_reader'
  get 'signupreader'  => 'readers#new'
  post 'create_reader'  => 'readers#create'


#mypage configuration

  namespace :mypage do
    resources :users do
      resources :articles do
        resources :comments
      end
    end
  end
  
  post '/mypage/users/:user_id/articles', to: 'mypage/articles#create', as: 'create_mypage_user_article'
  patch '/mypage/users/:user_id/articles/:id', to: 'mypage/articles#update', as: 'update_mypage_user_article'
  
  post '/mypage/users/:user_id/articles/:article_id/comments', to: 'mypage/comments#create', as: 'create_mypage_user_article_comment'
  patch '/mypage/users/:user_id/articles/:article_id/comments/:id', to: 'mypage/comments#update', as: 'update_mypage_user_article_comment'
  
  get '/mypage/users/:user_id/configurations', to: 'mypage/configurations#show', as: 'mypage_user_configuration'
  get '/mypage/users/:user_id/configurations/edit', to: 'mypage/configurations#edit', as: 'edit_mypage_user_configuration'
  patch '/mypage/users/:user_id/configurations', to: 'mypage/configurations#update', as: 'update_mypage_user_configuration'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @contents = []
    @users = User.all
    @articles = Article.all
    @comments = Comment.all.order(created_at: :desc)
    @comments.each do |comment|
      @content = {}
      @content["comment"] = comment
      @content["article"] = @articles.find_by(id: comment.article_id)
      @content["user"] = @users.find_by(id: @articles.find_by(id: comment.article_id).user_id)
      @contents.push(@content)
    end
    
    @contents1 = []
    @articles = Article.all.order("RANDOM()").where(status: true)
    @articles.each do |article|
      @content1 = {}
      @content1["article"] = article
      @content1["user"] = @users.find_by(id: article.user_id)
      @contents1.push(@content1)
    end
    
    @tweetscountofarticle = 0
    @articles = Article.all
    @articles.each do |article|
      article.comments.each do |comment|
        @tweetscountofarticle += comment.tweets.where(created_at: 1.weeks.ago..Time.now).count
      end
      article.update(comment_count_weekly: @tweetscountofarticle)
      @tweetscountofarticle = 0
    end
    @contents2 = []
    @articles = Article.all.order(comment_count_weekly: :desc).limit(10)
    @articles.each do |article|
      @content2 = {}
      @content2["article"] = article
      @content2["user"] = @users.find_by(id: article.user_id)
      @contents2.push(@content2)
    end
    
    @contents3 = []
    @articles = Article.all.order(comments_count_total: :desc).limit(10)
    @articles.each do |article|
      @content3 = {}
      @content3["article"] = article
      @content3["user"] = @users.find_by(id: article.user_id)
      @contents3.push(@content3)
    end

  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<% provide(:title, "NovelLabホーム") %>
  <div class="container2">
    <nav id="nav2">
      <a href="#1">新着の更新</a>
      <a href="#2">完結済み小説</a>
      <a href="#3">ランキング</a>
    </nav>
  </div>
  <div class="dummy">
  </div>
  <div class="intro">
    <div class="itro_text">
      <h1 id="logo2">NovelLab</h1>
      <p>小説を無料で読み書きできるサイトです。</p>
      <div class="writer_login">
        <p>作者の方へ</p>
        <p><%= link_to "作者新規登録", signup_path, id: "w-signin2" %></p>
        <p><%= link_to "作者ログイン", login_path, id: "w-login2"  %></p>
      </div>
      <div class="reader_login">
        <p>読者の方へ</p>
        <p><%= link_to "読者新規登録", signupreader_path, id: "r-signin2"  %></p>
        <p><%= link_to "読者ログイン", login_reader_path, id: "r-login2"  %></p>
      </div>
    </div>
  </div>
</header>
<div class="welcom_main">
  <div class="main1">
    <h1 id="1">更新された連載中小説</h1>
    <% @contents.each do |content| %>
    <div class="update">
      <p>
        <%= link_to content["article"].title, user_article_path(content["user"], content["article"]) %>  
        <span>コメント数：<%= content["article"].comments_count_total %></span>  
        <%= content["article"].category %> by <%= link_to content["user"].name, user_path(content["user"]) %>
      </p>
    </div>
    <% end %>
  </div>
  <div class="main2">  
    <h1  id="2">完結済みの小説</h1>
    <% @contents1.each do |content1| %>
    <div class="comp">
      <div id="left">
        <p class="comptitle"><%= link_to content1["article"].title, user_article_path(content1["user"], content1["article"]) %></p>
        <p class="compcategory"><%= content1["article"].category %></p>
        <p class="compname">by <%= link_to content1["user"].name, user_path(content1["user"]) %></p>
      </div>
      <div id="right">
        <p class="compabst"><%= content1["article"].text %></p>
      </div>
    </div>
    <% end %>
  </div>
  <div class="main3">  
    <h1 id="3">週間ランキング</h1>
    <% @contents2.each_with_index do |content2, i| %>
      <div id="rankweek<%=i+1%>">
        <p class="rankicon"><%= i+1 %></p>
        <p class="ranktitle"><%= link_to content2["article"].title, user_article_path(content2["user"], content2["article"]) %></p>
        <p class="rankcategory"><%= content2["article"].category %></p>
        <p class="rankname">by <%= link_to content2["user"].name, user_path(content2["user"]) %></p>
      </div>
    <% end %>
  </div>
  <div class="main4">
    <h1 id="4">総合ランキング</h1>
    <% @contents3.each_with_index do |content3, i| %>
      <div id="ranktotal<%=i+1%>">
        <p class="rankicon"><%= i+1 %></p>
        <p class="ranktitle"><%= link_to content3["article"].title, user_article_path(content3["user"], content3["article"]) %></p>
        <p class="rankcategory"><%= content3["article"].category %></p>
        <p class="rankname">by <%= link_to content3["user"].name, user_path(content3["user"]) %></p>
      </div>
    <% end %>
  </div>
</div>